version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://taskuser:password@db/tasktracker
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tasktracker
    ports:
      - "5432:5432"
